version: '3.8'
services:
  mysql-user:
    image: mysql
    container_name: mysql-user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3308:3306"
    volumes:
      - user-data:/var/lib/mysql

volumes:
  user-data: